# -*- coding: utf-8 -*-
"""- Analyzing Data with Python NUMPY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ak74uWUtWLglt2mD7OSNvM4gsY-pW1po
"""

# Q - 1 Convert a 1D array to a 2D array with 2 rows

import numpy as np

arr = np.array([1,2,3,4,5,6])
result = arr.reshape(2, -1)
print(result)

"""Q2. Common items between a and b

"""

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.intersect1d(a, b)
print(result)

"""Q.3 Get all items between 5 and 10 from a."""

a = np.array([2, 6, 1, 9, 10, 3, 27])

result = a[(a >= 5) & (a <= 10)]
print(result)

"""Q.4 Limit the number of items printed in python NumPy array a to a maximum of 6
elements.

"""

np.set_printoptions(threshold=6)

a = np.arange(15)
print(a)

""" # PANDAS
1. Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

"""

import pandas as pd

ser = pd.Series(np.random.random(10))

print("Min:", ser.min())
print("25%:", ser.quantile(0.25))
print("Median:", ser.median())
print("75%:", ser.quantile(0.75))
print("Max:", ser.max())

"""2. Creating A Pandas Data Frame and Using Sample Data Sets


"""

data = {
    'Name': ['A', 'B', 'C'],
    'Age': [20, 21, 19]
}

df = pd.DataFrame(data)
print(df)

"""3. Using NumPy, create a Pandas Data Frame with five rows and three columns.

"""

arr = np.random.randint(1, 100, size=(5,3))
df = pd.DataFrame(arr, columns=['A','B','C'])
print(df)

"""Q - 4 For a Pandas Data Frame created from a NumPy array, what is the default behavior for
the labels for the columns? For the rows?

- For a Pandas DataFrame created directly from a NumPy array, the default behavior is:

Columns :
0, 1, 2, 3, … (integers starting from 0)
Rows :
0, 1, 2, 3, … (integers starting from 0)

both starting from 0


"""

# Q - 4 ( EXAMPLES)
import numpy as np
import pandas as pd

arr = np.random.rand(4, 3)

df = pd.DataFrame(arr)

print(df)

"""take csv file contains at least 10,000 rows and 12 columns which numerical and text values
according to that continue following steps.

Q - 5 , 6 , 7
"""

import pandas as pd

df = pd.read_csv("/content/diamonds.csv")

df.head()

print(df.shape)

"""8. If you select a single column from the diamonds Data Frame, what will be the type of the
return value?
  ( pandas series )
  

"""

# type(df['column_name'])
df['carat']

"""Q - 9  Create a line plot using the x and y values provided below. Label the y-axis as “Y” and
label the x-axis as “X”.
x = [3, 4, 5, 6]
y = [1.5, 2, 2.5, 3]
"""

# LINE PLOT
import matplotlib.pyplot as plt

x = [3, 4, 5, 6]
y = [1.5, 2, 2.5, 3]

plt.plot(x, y)
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

""" Q - 10 Create an array of numbers between 0 and 6 with increments of 0.3 and name its “x”.
Then on the same plot, plot x, x², x³, and x⁴. For consistency, use the following style lines
respectively, “ro”, “bs”, “g”, and “:”. Lastly, make sure that the x-axis covers 0 to 6, while
the y-axis spans from 0 to 125. Do not worry if you are not familiar with the style lines —
you will recognize them as soon as you see the plot.
"""

import numpy as np
import matplotlib.pyplot as plt

# Create the x array: 0 to 6 with steps of 0.3
x = np.arange(0, 6.1, 0.3)   # 6.1 to make sure 6.0 is included

# Calculate the four functions
y1 = x          # x¹
y2 = x**2       # x²
y3 = x**3       # x³
y4 = x**4       # x⁴

# Create the plot
plt.figure(figsize=(10, 6))

plt.plot(x, y1, 'ro', label='x', markersize=6)
plt.plot(x, y2, 'bs', label='x²', markersize=6)
plt.plot(x, y3, 'g',  label='x³', linewidth=2.2)
plt.plot(x, y4, ':',  label='x⁴', linewidth=2.5, color='purple')

# Set axis limits
plt.xlim(0, 6)
plt.ylim(0, 125)

# Add labels and legend
plt.xlabel('x')
plt.ylabel('y')
plt.title('x, x², x³, x⁴ for x from 0 to 6')
plt.grid(True, alpha=0.3)
plt.legend()

plt.show()

"""Q - 11
 Heights and initials of a group of individuals are provided below. Create a bar plot titled
“Height Comparison” to compare the heights among this group.
height = [179, 155, 191, 152, 188, 177]
names = ['QA', 'WB', 'EC', 'RD', 'TE', 'YF']

"""

height = [179, 155, 191, 152, 188, 177]
names = ['QA', 'WB', 'EC', 'RD', 'TE', 'YF']

plt.bar(names, height)
plt.title("Height Comparison")
plt.show()

"""Q - 12
. Plot a histogram of x, where x consists of 100,000 randomly-selected points with a normal
distribution (hint: you can use numpy.random.randn() to generate the random points). The
histogram should have 10 bins. Look at how the histogram changes when we try 20 and 50
bins.
"""

x = np.random.randn(100000)

plt.hist(x, bins=15)
plt.show()

plt.hist(x, bins=25)
plt.show()

plt.hist(x, bins=55)
plt.show()

"""# THEORY

**Q - 13  What are the features of TensorFlow?**

Open-source ML framework

Supports deep learning & neural networks

GPU/TPU acceleration

Scalable

Works on multiple platforms

Automatic differentiation

Large community support

**Q - 14 Limitations of TensorFlow**

Complex for beginners

Debugging is difficult

Slower compared to some frameworks

Verbose syntax

Requires good hardware for large models

**Q - 15 What do you know about supervised and unsupervised machine learning?**

Supervised learning is a type of machine learning where the model is trained using labeled data.

This means the input data already has the correct output

Two types of supervised ml

**Classification** - Output is category

Example: Spam / Not Spam

**Regression** - Output is continuous value

Example: House price prediction


**Examples**

Email spam detection

Image classification

Predicting stock prices

**Algorithms Has been used **

Linear Regression

Logistic Regression

Decision Trees

Support Vector Machine (SVM)

**Advantages**

High accuracy when labeled data is available

Easy to evaluate

**Disadvantages**

Requires large labeled dataset

Data labeling is time-consuming



  **Unsupervised Learning**

Unsupervised learning is a type of machine learning where the model is trained using unlabeled data.
There is no predefined output.


two types of unsupervised ml

**Clustering** → Group similar data

Example: Customer segmentation

**Association** → Find relationships

Example: Market basket analysis


**Examples**

Customer segmentation

Recommendation systems

Anomaly detection

**Algorithms has been used**

K-Means Clustering

Hierarchical Clustering

DBSCAN

** Advantages**

No need for labeled data

Can discover hidden patterns


**Disadvantages**

Hard to evaluate accuracy

Results may not be easily interpretable
"""

